In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,4,5])
arr1.dtype

dtype('int64')

双重序列建立二维数组，三重序列建立三维数组

In [6]:
arr2 = np.array([[1,2,4,5],[5,6,7,8],[2,3,3,4]])
arr2

array([[1, 2, 4, 5],
       [5, 6, 7, 8],
       [2, 3, 3, 4]])

In [7]:
arr3 = np.array([[[1,2,4,5],[5,6,7,8],[4,5,6,7]],[[1,2,4,5],[5,6,7,8],[4,5,6,7]]])
arr3

array([[[1, 2, 4, 5],
        [5, 6, 7, 8],
        [4, 5, 6, 7]],

       [[1, 2, 4, 5],
        [5, 6, 7, 8],
        [4, 5, 6, 7]]])

ndarray.ndim：数组的维数（即数组轴的个数），等于秩
ndarray.shape：数组的维度。ndarray.shape返回一个元组，这个元组的长度就是维度的数目，即ndim属性。
ndarray.size：数组元素的总个数，等于shape属性中元组元素的乘积。
ndarray.dtype：表示数组中元素类型的对象

In [12]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

1
(4,)
4


In [13]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

2
(3, 4)
12


In [28]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr_copy = arr[5:15].copy()
arr[5:15] = 12
print(arr_copy)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4 12 12 12 12 12 12 12 12 12 12]


In [37]:
arr4 = np.arange(32).reshape((8,4))
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

调取row ————> 输入一个list
调取某个值 ————> 输入元组（即position）
负值(negative value) ————> 从矩阵末列开始调取，最后一列为-1

In [40]:
arr4[[3,2]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [46]:
print(arr4[3,2])
print(arr4[[1,4,2,7],[3,1,0,2]])

14
[ 7 17  8 30]


In [43]:
arr4[[-1,-2]]

array([[28, 29, 30, 31],
       [24, 25, 26, 27]])

In [47]:
arr4[np.ix_([1,5,7],[0,3,1])]

array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29]])

In [48]:
arr5 = np.random.randn(5,4)
arr5

array([[ 0.74227511,  0.34614593, -1.59948174,  1.88460378],
       [ 0.43934841,  0.25216529, -0.20934447, -0.72465202],
       [-1.29655419,  0.86359121,  0.42721358,  0.58568824],
       [ 1.61107921, -2.38667346, -0.30124311, -0.05123843],
       [-2.01633626, -0.59505577, -1.11583154, -0.05214661]])

In [49]:
arr5.mean()

-0.15982234182141647

In [52]:
arr5.mean(axis=1)

array([ 0.34338577, -0.0606207 ,  0.14498471, -0.28201895, -0.94484255])

In [53]:
arr5.sum(axis=0)

array([-0.52018773, -1.5198268 , -2.79868727,  1.64225496])

In [54]:
names = np.array(['Bob','Joe','Joe','Will','Joe','Will'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [4]:
import pandas as pd

In [12]:
obj1 = pd.Series([4,-7,5], index = [0,1,2])
obj1

0    4
1   -7
2    5
dtype: int64

In [13]:
obj1.values

array([ 4, -7,  5])

In [14]:
obj1.index

Int64Index([0, 1, 2], dtype='int64')

In [15]:
sdata = {'Ohil':35000,'Texas':71000,'Oregon':16000}
obj2 = pd.Series(sdata)
obj2

Ohil      35000
Oregon    16000
Texas     71000
dtype: int64

In [17]:
data = {'state':['Ohio','Ohio','Nevada'],
       'year':[2000,2001,2002],
       'pop':[1.5,1.7,2.9]}
obj3 = pd.DataFrame(data,index=['one','two','three'], columns=['year','state','pop'])
obj3

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002  Nevada  2.9

In [22]:
obj3.ix[0]
obj3.ix['one']

year     2000
state    Ohio
pop       1.5
Name: one, dtype: object

In [24]:
pop = {'Ohio':{2000:1.5, 2001:1.7},
      'Nevada':{2002:2.9}}
obj4 = pd.DataFrame(pop,)
obj4

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7
2002     2.9   NaN

In [26]:
index = obj4.index
index[1] = 2004

TypeError: Index does not support mutable operations

In [28]:
obj5 = pd.Series([4.5,7.4,3],index=['d','b','c'])
obj6 = obj5.reindex(['a','b','c','d'])
obj6

a    NaN
b    7.4
c    3.0
d    4.5
dtype: float64

In [32]:
obj7 = obj6.reindex(['a','b','c','d','e'])
obj7

a    NaN
b    7.4
c    3.0
d    4.5
e    NaN
dtype: float64

In [33]:
obj4

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7
2002     2.9   NaN

In [36]:
obj4.drop(2000)

Nevada  Ohio
2001     NaN   1.7
2002     2.9   NaN

In [39]:
obj4.drop('Nevada',axis=1)

Ohio
2000   1.5
2001   1.7
2002   NaN

In [72]:
obj4.loc[2001:2002,'Nevada':'Ohio']

Nevada  Ohio
2001     NaN   1.7
2002     2.9   NaN

In [55]:
print(obj4.iloc[1,1])
print(obj4.iloc[0:2,1])

1.7
2000    1.5
2001    1.7
Name: Ohio, dtype: float64


In [57]:
obj7 = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj7.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [60]:
obj8 = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj8.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [62]:
obj4

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7
2002     2.9   NaN

In [68]:
df = obj4.isin([1.5])
df

Nevada   Ohio
2000  False   True
2001  False  False
2002  False  False

In [70]:
obj4[df]

Nevada  Ohio
2000     NaN   1.5
2001     NaN   NaN
2002     NaN   NaN

In [74]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5,4.5,np.nan],index=['f','e','d','c','b','a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['f','e','d','c','b','a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [76]:
b[-1] = np.nan

In [80]:
print(a)
print(b)

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64


In [78]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [79]:
a[2:]

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [81]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [82]:
a[2:].combine_first(b[:-2])

a    NaN
b    4.5
c    3.5
d    2.0
e    1.0
f    0.0
dtype: float64

In [86]:
s1 = pd.Series([0,1,2,3], index=['a','b','c','d'])
s2 = pd.Series([4,5,6], index=['c','d','e'])
data2 = pd.concat([s1,s2])
data2

a    0
b    1
c    2
d    3
c    4
d    5
e    6
dtype: int64

In [88]:
data3 = pd.concat([s1,s2],axis=1)
data3

0    1
a  0.0  NaN
b  1.0  NaN
c  2.0  4.0
d  3.0  5.0
e  NaN  6.0

In [90]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), 
                    index=[['a','a','b','b'],[1,2,1,2]], 
                     columns = [['Ohio','Ohio','Colorado'],['Green','Red','Green']]
                    )
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [92]:
data = pd.DataFrame(np.arange(6).reshape((2,3)),
                   index = pd.Index(['Ohio','Colorado'], name='state'),
                   columns = pd.Index(['one','two','three'], name='number'))
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [93]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [94]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [95]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])